### ISSUE TITLE
[ledger_data] Premature Encounter of Non-Specified Marker

### ISSUE THREAD

**Issue by injaelee** [XRPLF/clio#166] opened 2022-05-31 19:08 UTC
# Observation
- Upon making a series of “ledger_data” request, a non-specified “marker” is encountered earlier than expected.
```bash
-- example: limit = 1_000
--

[1] Index:[72026703] Marker:[000105AEB72C725977020C7BDF471239765739B4D7513AE584BD1BAE328E5EC2]
[2] Index:[72026703] Marker:[00021792C00F50CE5219339AD4D6FC214CDFC59FBC396449F2903BD88205BBEE]
... omitted ...
[62] Index:[72026703] Marker:[003FA4B6C50F2E26AA79D4CF3A52C85FF591905FC52C4C8FE142881F95F0F5DE]
[63] Index:[72026703] Marker:[None]
```
- Individual subsequent call actually returns a marker.

```python
from xrpl.models.requests.ledger_data import LedgerData
from xrpl.clients.json_rpc_client import JsonRpcClient

client = JsonRpcClient("https://s1.ripple.com:51234/")

current_ledger_index = 72026703
current_marker = None
req = LedgerData(
    ledger_index = 72026703,
    marker = "003FA4B6C50F2E26AA79D4CF3A52C85FF591905FC52C4C8FE142881F95F0F5DE",
)
response = client.request(req)
print(response.result.get("marker"))
-- output: 0040CF920FC4DC78D0BA9AF47889483C376E41BA79FFA8BE301A780E3E83619C
```

# Expected Behavior
- Expect to only encounter a non-specified “marker” when all ledger objects are fetched for a given ledger index

# Reproduction Script
```python
from xrpl.models.requests.ledger_data import LedgerData
from xrpl.clients.json_rpc_client import JsonRpcClient
import logging
import time

logger = logging.getLogger(__name__)

client = JsonRpcClient("https://s1.ripple.com:51234/")

current_ledger_index = 72026703
current_marker = None
req = LedgerData(
    ledger_index = current_ledger_index,
)
request_count = 0
while req: # while there is a request keep fetching
    try:
        response = client.request(req)
        if not response.is_successful():
            raise RuntimeError("Response was not successful.")

        request_count += 1

        message = response.result
        current_ledger_index = message.get("ledger_index")
        current_marker = message.get("marker")

        print(f"[{request_count}] Index:[{current_ledger_index}] Marker:[{current_marker}]")
        if not current_marker:
            logger.info("[XRPLedgerObjectFetcher] No marker given. End of iteration.")
            req = None
            continue

        req = LedgerData(
            ledger_index = current_ledger_index,
            marker = current_marker,
        )

    except Exception as exp:
        logger.error(f"[{request_count}] Received message has failure: {exp}. Sleeping.")
        time.sleep(10)
        continue

```

**Comment by cjcobb23** [comment] 2022-06-27 17:51
So this is probably from passing markers to s1.ripple.com, where some servers are reporting mode and some are clio. Markers are not actually usable between different servers. If you use websocket, that should alleviate this issue, since websocket will pin you to one server.

**Comment by cindyyan317** [comment] 2023-04-17 13:47
Can't reproduce this bug. Close this issue. If it happens again, please feel free to reopen it.

The log I get is:
[1] Index:[72026703] Marker:[00005509683D83E05EB02641F59659D1010E1948A9B74C36DFC16058D7BCF62C]
[2] Index:[72026703] Marker:[00044EE0C04536A82A87D32CD8BB32DB0ABF9CA395E24A9AA766AFF5EC1C1CDA]
[3] Index:[72026703] Marker:[0007F33BC6B77AEDC05C0E65C5F9AC01EC21070AFCEA27BE45DB5D949A631AF3]
[4] Index:[72026703] Marker:[000BE843D16C291840C865C8234CF8B6640945061A7AE474BDC7E305929B213D]
[5] Index:[72026703] Marker:[000FE5ED4F0E59D865F933C1B1484FDDDC35637ADBEDBF760B9679E151B00548]
[6] Index:[72026703] Marker:[0013EC265AC84BF8E06B11706C64EBD86FA08564B1E2E6831F66C9D7FF926FA9]
[7] Index:[72026703] Marker:[00180BCC3B36299DBFD7BDAAB099D48D09F545558E5D99EA6A695BFA163058F8]
[8] Index:[72026703] Marker:[001C18C11F97A5DB5CE2F2B1C7A7D6C2BEF904607AC1EC7572F60828019AF9B8]
[9] Index:[72026703] Marker:[00201A57CB91B652081A12753EEF7207073CA5FE3CD05076CA17DF6B8BE8009D]
[10] Index:[72026703] Marker:[00242873FF942A5D7745212A406E3FB7EF3CDE140F3691A12EDFE8F440B796E2]
[11] Index:[72026703] Marker:[00286A70F5D0E9EE2766E99C9EB28F8C60653DBDBC68E0C31D9309A4D1073341]
[12] Index:[72026703] Marker:[002C88E335BB8B29C84A5B4CD98E31AE030E6E9C675C2C7904F2AD502E763D32]
[13] Index:[72026703] Marker:[00307F253246B8D40E174A984D6DF79814ACCA36487E6B47B97F0A4E0876CDCA]
[14] Index:[72026703] Marker:[00348F114B80402E6F07A5696B23E1111224DF2381E05E977151F7FB8AF81531]
[15] Index:[72026703] Marker:[003853F23BA4E1D0BB321CEB51EEDB200B592A3A04C313F6544FF2838ABFE27F]
[16] Index:[72026703] Marker:[003C9C7395A1FF40452EBA0E7D68834526054904E05F5D0553D1BB226A1FB79A]
[17] Index:[72026703] Marker:[0040B09B243CCEC2487C5095F5B7443E317AEB1C25627238844C74E2ABB625A2]
[18] Index:[72026703] Marker:[0044C59F79EFFE783D8B5EB95D64E6411591B4C53A673C47F67855B49B4A07D6]
[19] Index:[72026703] Marker:[004906E9166DCD8E6E1F53859A03F60F35C55EFBC0F4BB6EE9FA8496F7DFBA29]
[20] Index:[72026703] Marker:[004D11A51D5CF93E0C1E5E81017144DFA9FADBD9939CCA13723FBB756ED30195]
[21] Index:[72026703] Marker:[0050DEF23DE93560F8EC45677ABDCB9922A7932621939E2D3B0B4BCBA6CE29D1]
[22] Index:[72026703] Marker:[0054CEF381466B2EEE7FF03400CCD15DB0B09EB2289FDB3ED1E3BD1C3C01E5A3]
[23] Index:[72026703] Marker:[0058E5BEAC7AE030B59910A68F69418563B7976FCE7F11400095F82B5CD786C5]
[24] Index:[72026703] Marker:[005CD3EE79C93D56899737E3D0D27493D093FEA6FCF5E63343C1E12B54C6A109]
[25] Index:[72026703] Marker:[0061009AF1BA7F86780D49AEF683A3C4E2590A4F1350E37E5CD9625A17C0E4C9]
[26] Index:[72026703] Marker:[006502F9D3E82706C545AF47E782781EF0544FCF6FA5B3852671E9C83F6C37C1]
[27] Index:[72026703] Marker:[00691AE460D53D28FC85B81C2C7E2DFF7FDF7342926AC533871F3003FFBD2AD7]
[28] Index:[72026703] Marker:[006D0B99E7E82C0FE108940C5C5076A5D6A3921E01D5B9725CE676A8EFA4B36B]
[29] Index:[72026703] Marker:[007101F9CD270FADA7E22D997048C582EF7DCA043E25F324D76DA0308E3B3744]
[30] Index:[72026703] Marker:[0074FD7A3FCB2625207A199439A034DCF4B2DA3C6338BBB98653E8DC2A69733D]
[31] Index:[72026703] Marker:[0078FDFB3B376305F5F9EFEC90DE566F6455BB7197A73DDDC8655889239D9CBF]
[32] Index:[72026703] Marker:[007D14ED7E69A381421AB891CAE630C94D520E23845371F776011CD13C3F54CA]
[33] Index:[72026703] Marker:[008156BFB5640BBE4467864607BF721DBECF9543390EDD33BFD8DB88A3553067]
[34] Index:[72026703] Marker:[00851A169FC4F3D14F21662CE9AC880FB0B1A858F2AD776648FDA6ABED71D7CC]
[35] Index:[72026703] Marker:[00892B56C9F3EC2CF94EA20E9C5BA5EEBA5057F95E301303ABEC62D5D0AF1AD5]
[36] Index:[72026703] Marker:[008D3712BD2C38B0BE2922047CE7290DFE55F245A0788C296B6754BE9C43780D]
[37] Index:[72026703] Marker:[0090FFDA9003F2A7C7121BB0C31D42BC8581F56D6D3B25182F2BB13CD7372341]
[38] Index:[72026703] Marker:[00951F9EF3D807ED487170A7D0BA16D722B0B833AE0BC7DDD0771F995E5E28CC]
[39] Index:[72026703] Marker:[009938E5C511243DA159DEA466F8841FC7F5BFA767A7A4FAC050A40DAB4D9DE1]
[40] Index:[72026703] Marker:[009D49347E7FA787A047FB9E85A6B2A2C60D8F1EF388449610C5A4D1A2CD7532]
[41] Index:[72026703] Marker:[00A12F5192DC07DDF1F0EF26F92455E8340FF707321111031EF5EC1FCB3A2665]
[42] Index:[72026703] Marker:[00A549FC9404A45515C8A44AAE1284B54C01494C9CCB9B674DD20BA129DDC690]
[43] Index:[72026703] Marker:[00A948F54FF95EEE00685A899109794F34B406B742DEC51400F747C68363B8A9]
[44] Index:[72026703] Marker:[00AD65D4FFF60374C93B0C284E91EFF4BFFBBC00426792CE4A597508DE49251E]
[45] Index:[72026703] Marker:[00B18EF3DA8760294E701A98578197FF16BB7F6EC417F0E9B4B04FC80BA70312]
[46] Index:[72026703] Marker:[00B58EC2BE95F1A3D38928F59F155051DD46DD4531466144079A0B6FBE8CC6AC]
[47] Index:[72026703] Marker:[00B8279757AB98274EE69D7484BE0FACA80094E10C7DA2751132227122479899]
[48] Index:[72026703] Marker:[00BC6C794056A02D099830B16699955B9062178F618835DBB96F7E48F72FF1CD]
[49] Index:[72026703] Marker:[00C05B387562A64DC2E3C0A7FE74FF0892C0A2F317226A26A5A47C8A60876C7E]
[50] Index:[72026703] Marker:[00C460A0C49E142E254BA861094AF38EABBEEAC6BE80F3B2424220D68464B830]
[51] Index:[72026703] Marker:[00C87E3507903B57C4E12B52171328A16C1B11957EEB94B2D067A6A275A41992]
[52] Index:[72026703] Marker:[00CC69C9D17B098EE981001A3569586C814EFEA97E176AE227FC3BF8513BECA1]
[53] Index:[72026703] Marker:[00D071A89A2F81181350BDE0B2F0A9257EE0BDF6B42D43501EFFC0784C4FE0AB]
[54] Index:[72026703] Marker:[00D4610A12A598B6A6B2DB2CF487A39D176ACDADBCC2E30B71CF39DBFCD5FBB4]
[55] Index:[72026703] Marker:[00D870743CC7CEA3F97CA1EFAD5985CA3EE050D5E974EDF508BD3F09BE1F36C1]
[56] Index:[72026703] Marker:[00DC89D9ACCB4F50B30CED84E865BBBB64902194E2FA265F7F4563BCEB75C57A]
[57] Index:[72026703] Marker:[00E086259D81C041906A85C675932E2EAC7E6FE074B97FB8452B9E53C1631E51]
[58] Index:[72026703] Marker:[00E4ACE93673763439115E85638E02C1BFCB03F2ECC490F21A6A59849FE6E312]
[59] Index:[72026703] Marker:[00E86C938BA9ABDE45830AB7C6CB0905C001586D25A57C89A6724883AC29F50C]
[60] Index:[72026703] Marker:[00EC7661640A4426050B873267D62A210949A9FE104DD6749E69944866278C1B]
[61] Index:[72026703] Marker:[00F061FCAF2D490AE9B5E32A0024A800AF4804D315784A775B5DAE6FBBE96013]
[62] Index:[72026703] Marker:[00F45B52945DB790711676A8B48F0D2043FB6794E6C36D567AA5F4C288049715]
[63] Index:[72026703] Marker:[00F83375D47AD7082932CB440A17BA3C4B84DE83A2389E2350543C0263FF2EC0]
[64] Index:[72026703] Marker:[00FC5A94997060EC2799BCDB5B7955635784A2E10AD49CA3D86CEE21808084E3]
[65] Index:[72026703] Marker:[01003F6E97FD3C577A89E195694F2D24DD8E9F52177517991876686B2FEBA756]
[66] Index:[72026703] Marker:[010444BA8665BD95B202642E12143A2A1F8F74ECE9901D32AA31E6C55DA84CDE]
[67] Index:[72026703] Marker:[0108721C9912226095142913483A00AD08A5B944D7DDC1A4672162419F95A05A]
...

**Closed as completed by cindyyan317** 2023-04-17 13:47 UTC
Labels: bug
