### ISSUE TITLE
subscribe to accounts_proposed with empty accounts_proposed is not returning an error

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#350] opened 2022-10-06 22:24 UTC
sample request:
`{
  "id": "Example watch Bitstamp's hot wallet",
  "command": "subscribe",
  "accounts_proposed": []
}`

response:
`{
  "id": "Example watch Bitstamp's hot wallet",
  "result": {
    "validated": true
  },
  "status": "success",
  "type": "response",
  "warnings": [
    {
      "id": 2001,
      "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
    }
  ]
}`

expected response:
`{
  "error": "actMalformed",
  "error_code": 35,
  "error_message": "Account malformed.",
  "id": "Example watch Bitstamp's hot wallet",
  "request": {
    "accounts_proposed": [
      
    ],
    "command": "subscribe",
    "id": "Example watch Bitstamp's hot wallet"
  },
  "status": "error",
  "type": "response"
}`

**Comment by godexsoft** [comment] 2022-11-04 16:17
Duplicate of #347

**Closed as completed by godexsoft** 2022-11-04 16:17 UTC
