### ISSUE TITLE
Missing `amm` type filter in `account_objects`

### ISSUE THREAD

**Issue by mvadari** [XRPLF/clio#902] opened 2023-10-06 23:20 UTC
This is the response I get when I try to ping Clio about AMM objects for an account (this is on mainnet so maybe there's an "amendment enabled" specific check?):
```
{
    error: 'invalidParams',
    error_code: 31,
    error_message: 'Invalid parameters.',
    status: 'error',
    type: 'response',
    id: 1,
    request: {
      command: 'account_objects',
      account: 'rJumr5e1HwiuV543H7bqixhtFreChWTaHH',
      type: 'amm',
      id: 1
    },
    warnings: [
      {
        id: 2001,
        message: "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
      }
    ]
  }
}

**Comment by godexsoft** [comment] 2023-10-09 10:11
Sounds like a duplicate of #834.
@arihantkothari is working on #283 and was asked to also remember to incorporate changes from https://github.com/XRPLF/rippled/pull/4682.
Please also note that this is targeting Clio 2.1.

**Closed as completed by godexsoft** 2023-10-09 10:11 UTC
Labels: duplicate
